
BACKUP_TO = $(subst $(PREFIX),$(PREFIX)/backup,$(shell pwd))

backup:
	mkdir -p $(BACKUP_TO)
	$(foreach FILE, $(SAVED_FILES), cp $(FILE) $(BACKUP_TO)/$(FILE);)
	$(foreach DIR, $(SAVED_DIRS), $(MAKE) -C  $(DIR) backup;)
