# Makefile for the AOPify pass
ROOT=../..

include $(ROOT)/Makefile.inc

PASSNAME := decorate_pass
OBJS := decorate_pass.o

IFLAGS := -I$(INCLUDE_WRAPPER_DIR)/$(KERNEL_BUILD_TYPE)


include ../Makefile.inc


